apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: test
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 80
      name: http-web
      nodePort: 30007
