apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 5m
  chart:
    spec:
      chart: openebs
      #version: 1.6.0
      sourceRef:
        kind: HelmRepository
        name: openebs-chart
        namespace: flux-system
      interval: 10m
