apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 5m
  chart:
    spec:
      chart: openebs/openebs
      version: 1.6.0
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: openebs
      interval: 10m
