apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      #version: 3.0.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: monitoring
      interval: 10m
  values:
    prometheus:
      service:
        type: NodePort
    grafana:
      service:
        type: NodePort
